
import "./styles.css";
import Link from 'next/link'
import { HeaderTest } from './header'
import Header from './[locale]/modules/Header'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <HeaderTest />
        {/* <Header/> */}
          {children}
      </body>
    </html>
  )
}
